server: 
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: vehicle-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/vehicles/**

        - id: reservation-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/reservations/**

        - id: infraction-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/infracciones/**
      
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
